### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sifodev** [insaneshadowzaman/Traffic-Rules-Violation-Detection#13]
Traceback (most recent call last):
  File "/home/kotai001/traffic_violationv2/MainWindow.py", line 177, in update_image
    packet = self.processor.getProcessedImage(frame)
  File "/home/kotai001/traffic_violationv2/processor/MainProcessor.py", line 30, in getProcessedImage
    dicti = self.processor.cross_violation(frame)
  File "/home/kotai001/traffic_violationv2/processor/TrafficProcessor.py", line 32, in cross_violation
    self.frame = imutils.resize(frame, width=500)
  File "/home/kotai001/traffic_violationv2/venv/lib/python3.6/site-packages/imutils/convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

getting this error after running the app sometime

**Comment by praneeti06** [comment]
hi can you tell me how you solve this issue
its really urgent and I'm also getting this same issue so can you please help me

**Comment by mandarc64** [comment]
It's because of the duration of the video. If the video is of 30 seconds and the line in MainWindow.py is like `self.timer.start(50)` then the video will run for 60 seconds and will give you this error. So make it 100, at least the project will run for more than 2 minutes.

**Comment by sherali199203** [comment]
PS C:\chorraha\Yo'l harakati qoidalarini buzish - aniqlash\Traffic-Rules-Violation-Detection-master> & C:/Users/Sherali/AppData/Local/Programs/Python/Python312/python.exe "c:/chorraha/Yo'l harakati qoidalarini buzish - aniqlash/Traffic-Rules-Violation-Detection-master/main.py"
Traceback (most recent call last):
  File "c:\chorraha\Yo'l harakati qoidalarini buzish - aniqlash\Traffic-Rules-Violation-Detection-master\MainWindow.py", line 177, in update_image
    packet = self.processor.getProcessedImage(frame)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\chorraha\Yo'l harakati qoidalarini buzish - aniqlash\Traffic-Rules-Violation-Detection-master\processor\MainProcessor.py", line 30, in getProcessedImage
    dicti = self.processor.cross_violation(frame)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\chorraha\Yo'l harakati qoidalarini buzish - aniqlash\Traffic-Rules-Violation-Detection-master\processor\TrafficProcessor.py", line 32, in cross_violation
    self.frame = imutils.resize(frame, width=500)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sherali\AppData\Local\Programs\Python\Python312\Lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
             ^^^^^^^^^^^

**Comment by sherali199203** [comment]
I get this error, can you help me?
