### ISSUE TITLE
 am getting this error sqlite3.OperationalError: no such column: false

### ISSUE THREAD

**Issue by aub8016** [insaneshadowzaman/Traffic-Rules-Violation-Detection#3]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 9, in main
    main_window = MainWindow()
  File "/home/aub/backup/Traffic-Rules-Violation-Detection/MainWindow.py", line 68, in __init__
    self.updateLog()
  File "/home/aub/backup/Traffic-Rules-Violation-Detection/MainWindow.py", line 205, in updateLog
    rows = self.database.getViolationsFromCam(str(self.cam_selector.currentText()))
  File "/home/aub/backup/Traffic-Rules-Violation-Detection/Database.py", line 154, in getViolationsFromCam
    cur.execute(command)
sqlite3.OperationalError: no such column: false

**Comment by NayanDoshi** [comment]
same error

Are you get any solution

**Comment by ivan95603** [comment]
@aub8016 @NayanDoshi check the pull request for the fix https://github.com/rahatzamancse/Traffic-Rules-Violation-Detection/pull/7

**Comment by aanchal9202** [comment]
Traceback (most recent call last):
  File "C:/Users/aanchal/PycharmProjects/work/venv/Traffic-Rules-Violation-Detection-master/main.py", line 16, in <module>
    main()
  File "C:/Users/aanchal/PycharmProjects/work/venv/Traffic-Rules-Violation-Detection-master/main.py", line 9, in main
    main_window = MainWindow()
  File "C:\Users\aanchal\PycharmProjects\work\venv\Traffic-Rules-Violation-Detection-master\MainWindow.py", line 68, in __init__
    self.updateLog()
  File "C:\Users\aanchal\PycharmProjects\work\venv\Traffic-Rules-Violation-Detection-master\MainWindow.py", line 205, in updateLog
    rows = self.database.get_violations_from_cam(str(self.cam_selector.currentText()))
  File "C:\Users\aanchal\PycharmProjects\work\venv\Traffic-Rules-Violation-Detection-master\Database.py", line 150, in get_violations_from_cam
    cur.execute(command)
sqlite3.OperationalError: no such column: false


i also get error in it

**Comment by 1advait** [comment]
getting the same error if you both have the solution please tell me that

**Comment by sifodev** [comment]
getting the same error please help

**Comment by yukilulu** [comment]
getting the same error, please tell me how to fix it please.
